# This is a basic workflow to help you get started with Actions

name: Build latest Spigot JAR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
  schedule:
    - cron: '0 9,12,16,20 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '16'
    
    - name: Build Spigot Release Jar
      run: ./run.sh
    
    - name: Upload a Build Artifact to Azure Blob Storage
      uses: fixpoint/azblob-upload-artifact@v4
      with:
        # Connection string
        connection-string: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
        name: releases
        path: output
        container: spigot
        cleanup: false

